# Generated by Django 5.1.1 on 2024-09-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectscheduleitemmark',
            options={'ordering': ['is_editing', 'subject_item']},
        ),
        migrations.AddField(
            model_name='subjectscheduleitemmark',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.botuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectscheduleitemmark',
            name='is_editing',
            field=models.BooleanField(default=False, verbose_name='Is editing'),
        ),
    ]
